### ISSUE TITLE
Issue with scappy and the SYN flooding

### ISSUE THREAD

**Issue by MarkAppprogrammer** [MarkAppprogrammer/NetworkScannerbyMark#1]
When I try to do the syn flooding it says this
```
Traceback (most recent call last):
  File "/home/pi/pentest/NetScan/netscan.py", line 578, in <module>
    homescreen()
  File "/home/pi/pentest/NetScan/netscan.py", line 562, in homescreen
    basicnettests()
  File "/home/pi/pentest/NetScan/netscan.py", line 438, in basicnettests
    tcp = scapy.TCP(dst_port = target_port, flags = "S")
  File "/home/pi/.local/lib/python3.9/site-packages/scapy/base_classes.py", line 258, in __call__
    i.__init__(*args, **kargs)
  File "/home/pi/.local/lib/python3.9/site-packages/scapy/packet.py", line 157, in __init__
    for fname, _ in fields:
ValueError: too many values to unpack (expected 2)
```

**Comment by MarkAppprogrammer** [comment]
SYN Flooding is no longer avalible
